- name: Ensure Docker network exists
  docker_network:
    name: wordpress-network
    state: present

- name: Create directory for WordPress configuration
  file:
    path: /opt/wordpress
    state: directory
    mode: '0755'
  become: yes

- name: Create Docker volumes
  docker_volume:
    name: wordpress_data
    state: present

- name: Copy wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: /opt/wordpress/wp-config.php
    mode: '0644'
  become: yes

- name: Create WordPress container
  docker_container:
    name: wordpress
    image: wordpress:latest
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network }}"
      - name: "{{ mysql_cluster_network }}"
    published_ports:
      - "{{ wordpress_port }}:80"
    env:
      WORDPRESS_DB_HOST: mysql_primary:3307
      WORDPRESS_DB_NAME: "{{ database_name }}"
      WORDPRESS_DB_USER: "{{ database_user }}"
      WORDPRESS_DB_PASSWORD: "{{ database_password }}"
      WORDPRESS_DEBUG: "false"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('WP_CACHE', true);
        define('AUTOMATIC_UPDATER_DISABLED', true);
        define('WP_AUTO_UPDATE_CORE', false);
        define('DISALLOW_FILE_EDIT', true);
        define('DISALLOW_FILE_MODS', true);
        define('WP_CRON_LOCK_TIMEOUT', 60);
    volumes:
      - wordpress_data:/var/www/html
      - /opt/wordpress/wp-config.php:/var/www/html/wp-config.php
