- name: Ensure WordPress container is running
  docker_container:
    name: wordpress
    image: wordpress:latest
    restart_policy: always
    ports:
      - "8081:80"
    env:
      WORDPRESS_DB_HOST: "wordpress_db"
      WORDPRESS_DB_USER: "wordpress_user"
      WORDPRESS_DB_PASSWORD: "wordpress_password"
      WORDPRESS_DB_NAME: "wordpress_db"
    volumes:
      - wordpress_data:/var/www/html

- name: Ensure database container is running
  docker_container:
    name: wordpress_db
    image: mysql:5.7
    ports:
      - "3307:3307"
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "wordpress_db"
      MYSQL_USER: "wordpress_user"
      MYSQL_PASSWORD: "wordpress_password"
    volumes:
      - db_data:/var/lib/mysql

- name: Create Docker volumes
  docker_volume:
    name: "{{ item }}"
  loop:
    - wordpress_data
    - db_data