- name: Ensure Docker network exists
  docker_network:
    name: wordpress-network
    state: present

- name: Create Docker volumes
  docker_volume:
    name: wordpress_data
    state: present

- name: Copy wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: /tmp/wp-config.php

- name: Create WordPress container
  docker_container:
    name: wordpress
    image: wordpress:latest
    state: started
    restart_policy: always
    networks:
      - name: wordpress-network
      - name: db_cluster_network
    published_ports:
      - 8080:80
    volumes:
      - wordpress_data:/var/www/html
      - /tmp/wp-config.php:/var/www/html/wp-config.php
