- name: Ensure WordPress container is running
  docker_container:
    name: wordpress
    image: wordpress:latest
    restart_policy: always
    ports:
      - "8080:80"
    env:
      WORDPRESS_DB_HOST: "{{ db_host }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
      WORDPRESS_DB_NAME: "{{ db_name }}"
    volumes:
      - wordpress_data:/var/www/html

- name: Ensure database container is running
  docker_container:
    name: wordpress_db
    image: mysql:5.7
    restart_policy: always
    environment:
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
    volumes:
      - db_data:/var/lib/mysql

- name: Create Docker volumes
  docker_volume:
    name: "{{ item }}"
  loop:
    - wordpress_data
    - db_data