- name: Ensure database container is present
  docker_container:
    name: wordpress_db
    image: mysql:5.7
    state: present
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
    volumes:
      - db_data:/var/lib/mysql

- name: Create database volume
  docker_volume:
    name: db_data
    state: present

- name: Wait for MySQL to be ready
  wait_for:
    port: 3306
    delay: 10
    timeout: 300
    state: started